import { defineConfig } from "vite";
import { resolve } from "path";

const CLEAN_URLS = {
  "/dashboard": "/src/pages/dashboard.html",
  "/login": "/src/pages/login.html",
  "/register": "/src/pages/register.html",
  "/team": "/src/pages/team.html",
  "/level-designer": "/src/pages/level-designer.html",
  "/quest-generator": "/src/pages/quest-generator.html",
  "/texture-upscaler": "/src/pages/texture-upscaler.html",
  "/character-creator": "/src/pages/character-creator.html",
  "/sound-designer": "/src/pages/sound-designer.html",
  "/playtester": "/src/pages/playtester.html",
  "/localization": "/src/pages/localization.html",
  "/game-balancer": "/src/pages/game-balancer.html",
  "/level-analyzer": "/src/pages/level-analyzer.html",
  "/store-description": "/src/pages/store-description.html",
  "/playtest-analyzer": "/src/pages/playtest-analyzer.html",
  "/trailer-script": "/src/pages/trailer-script.html",
  "/review-analyzer": "/src/pages/review-analyzer.html",
  "/discord-bot": "/src/pages/discord-bot.html",
  "/reset-password": "/src/pages/reset-password.html",
  "/accept-invite": "/src/pages/accept-invite.html",
  "/ru": "/src/pages/ru/index.html",
  "/ru/": "/src/pages/ru/index.html",
  "/locforge": "/src/pages/locforge.html",
  "/ru/locforge": "/src/pages/ru/locforge.html",
  "/tools/level-designer": "/src/pages/tools/level-designer.html",
  "/tools/quest-generator": "/src/pages/tools/quest-generator.html",
  "/tools/texture-upscaler": "/src/pages/tools/texture-upscaler.html",
  "/tools/character-creator": "/src/pages/tools/character-creator.html",
  "/tools/sound-designer": "/src/pages/tools/sound-designer.html",
  "/tools/playtester": "/src/pages/tools/playtester.html",
  "/tools/localization": "/src/pages/tools/localization.html",
  "/tools/game-balancer": "/src/pages/tools/game-balancer.html",
  "/tools/level-analyzer": "/src/pages/tools/level-analyzer.html",
  "/tools/store-description": "/src/pages/tools/store-description.html",
  "/tools/playtest-analyzer": "/src/pages/tools/playtest-analyzer.html",
  "/tools/trailer-script": "/src/pages/tools/trailer-script.html",
  "/tools/review-analyzer": "/src/pages/tools/review-analyzer.html",
  "/tools/discord-bot": "/src/pages/tools/discord-bot.html",
  "/ru/tools/level-designer": "/src/pages/ru/tools/level-designer.html",
  "/ru/tools/quest-generator": "/src/pages/ru/tools/quest-generator.html",
  "/ru/tools/texture-upscaler": "/src/pages/ru/tools/texture-upscaler.html",
  "/ru/tools/character-creator": "/src/pages/ru/tools/character-creator.html",
  "/ru/tools/sound-designer": "/src/pages/ru/tools/sound-designer.html",
  "/ru/tools/playtester": "/src/pages/ru/tools/playtester.html",
  "/ru/tools/localization": "/src/pages/ru/tools/localization.html",
  "/ru/tools/game-balancer": "/src/pages/ru/tools/game-balancer.html",
  "/ru/tools/level-analyzer": "/src/pages/ru/tools/level-analyzer.html",
  "/ru/tools/store-description": "/src/pages/ru/tools/store-description.html",
  "/ru/tools/playtest-analyzer": "/src/pages/ru/tools/playtest-analyzer.html",
  "/ru/tools/trailer-script": "/src/pages/ru/tools/trailer-script.html",
  "/ru/tools/review-analyzer": "/src/pages/ru/tools/review-analyzer.html",
  "/ru/tools/discord-bot": "/src/pages/ru/tools/discord-bot.html",
  "/admin": "/src/pages/admin/dashboard.html",
  "/admin/login": "/src/pages/admin/login.html",
  "/admin/users": "/src/pages/admin/users.html",
  "/admin/user": "/src/pages/admin/user.html",
  "/admin/generations": "/src/pages/admin/generations.html",
  "/admin/generation": "/src/pages/admin/generation.html",
  "/admin/subscriptions": "/src/pages/admin/subscriptions.html",
  "/admin/tools": "/src/pages/admin/tools.html",
  "/admin/settings": "/src/pages/admin/settings.html",
  "/admin/ai-models": "/src/pages/admin/ai-models.html",
  "/admin/logs": "/src/pages/admin/logs.html",
  "/admin/content": "/src/pages/admin/content.html",
  "/admin/content/edit": "/src/pages/admin/content-edit.html",
  "/faq": "/src/pages/faq.html",
  "/blog": "/src/pages/blog.html",
  "/blog/post": "/src/pages/blog-post.html",
  "/offer": "/src/pages/offer.html",
  "/contacts": "/src/pages/contacts.html",
  "/ru/faq": "/src/pages/ru/faq.html",
  "/ru/blog": "/src/pages/ru/blog.html",
  "/ru/blog/post": "/src/pages/ru/blog-post.html",
  "/ru/offer": "/src/pages/ru/offer.html",
  "/ru/contacts": "/src/pages/ru/contacts.html",
};

function cleanUrlsPlugin() {
  return {
    name: "gameforge-clean-urls",
    configureServer(server) {
      server.middlewares.use((req, _res, next) => {
        const path = req.url?.split("?")[0];
        if (path && CLEAN_URLS[path]) {
          const qs = req.url.includes("?") ? req.url.slice(req.url.indexOf("?")) : "";
          req.url = CLEAN_URLS[path] + qs;
        }
        next();
      });
    },
  };
}

export default defineConfig({
  root: ".",
  publicDir: "public",
  plugins: [cleanUrlsPlugin()],
  build: {
    outDir: "dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        login: resolve(__dirname, "src/pages/login.html"),
        register: resolve(__dirname, "src/pages/register.html"),
        dashboard: resolve(__dirname, "src/pages/dashboard.html"),
        level: resolve(__dirname, "src/pages/level-designer.html"),
        quest: resolve(__dirname, "src/pages/quest-generator.html"),
        texture: resolve(__dirname, "src/pages/texture-upscaler.html"),
        character: resolve(__dirname, "src/pages/character-creator.html"),
        sound: resolve(__dirname, "src/pages/sound-designer.html"),
        playtester: resolve(__dirname, "src/pages/playtester.html"),
        localization: resolve(__dirname, "src/pages/localization.html"),
        gameBalancer: resolve(__dirname, "src/pages/game-balancer.html"),
        levelAnalyzer: resolve(__dirname, "src/pages/level-analyzer.html"),
        storeDescription: resolve(__dirname, "src/pages/store-description.html"),
        playtestAnalyzer: resolve(__dirname, "src/pages/playtest-analyzer.html"),
        trailerScript: resolve(__dirname, "src/pages/trailer-script.html"),
        reviewAnalyzer: resolve(__dirname, "src/pages/review-analyzer.html"),
        discordBot: resolve(__dirname, "src/pages/discord-bot.html"),
        resetPassword: resolve(__dirname, "src/pages/reset-password.html"),
        team: resolve(__dirname, "src/pages/team.html"),
        acceptInvite: resolve(__dirname, "src/pages/accept-invite.html"),
        ruLand: resolve(__dirname, "src/pages/ru/index.html"),
        locforge: resolve(__dirname, "src/pages/locforge.html"),
        ruLocforge: resolve(__dirname, "src/pages/ru/locforge.html"),
        toolLevel: resolve(__dirname, "src/pages/tools/level-designer.html"),
        toolQuest: resolve(__dirname, "src/pages/tools/quest-generator.html"),
        toolTexture: resolve(__dirname, "src/pages/tools/texture-upscaler.html"),
        toolCharacter: resolve(__dirname, "src/pages/tools/character-creator.html"),
        toolSound: resolve(__dirname, "src/pages/tools/sound-designer.html"),
        toolPlaytester: resolve(__dirname, "src/pages/tools/playtester.html"),
        toolLocalization: resolve(__dirname, "src/pages/tools/localization.html"),
        toolGameBalancer: resolve(__dirname, "src/pages/tools/game-balancer.html"),
        toolLevelAnalyzer: resolve(__dirname, "src/pages/tools/level-analyzer.html"),
        toolStoreDescription: resolve(__dirname, "src/pages/tools/store-description.html"),
        toolPlaytestAnalyzer: resolve(__dirname, "src/pages/tools/playtest-analyzer.html"),
        toolTrailerScript: resolve(__dirname, "src/pages/tools/trailer-script.html"),
        toolReviewAnalyzer: resolve(__dirname, "src/pages/tools/review-analyzer.html"),
        toolDiscordBot: resolve(__dirname, "src/pages/tools/discord-bot.html"),
        ruToolLevel: resolve(__dirname, "src/pages/ru/tools/level-designer.html"),
        ruToolQuest: resolve(__dirname, "src/pages/ru/tools/quest-generator.html"),
        ruToolTexture: resolve(__dirname, "src/pages/ru/tools/texture-upscaler.html"),
        ruToolCharacter: resolve(__dirname, "src/pages/ru/tools/character-creator.html"),
        ruToolSound: resolve(__dirname, "src/pages/ru/tools/sound-designer.html"),
        ruToolPlaytester: resolve(__dirname, "src/pages/ru/tools/playtester.html"),
        ruToolLocalization: resolve(__dirname, "src/pages/ru/tools/localization.html"),
        ruToolGameBalancer: resolve(__dirname, "src/pages/ru/tools/game-balancer.html"),
        ruToolLevelAnalyzer: resolve(__dirname, "src/pages/ru/tools/level-analyzer.html"),
        ruToolStoreDescription: resolve(__dirname, "src/pages/ru/tools/store-description.html"),
        ruToolPlaytestAnalyzer: resolve(__dirname, "src/pages/ru/tools/playtest-analyzer.html"),
        ruToolTrailerScript: resolve(__dirname, "src/pages/ru/tools/trailer-script.html"),
        ruToolReviewAnalyzer: resolve(__dirname, "src/pages/ru/tools/review-analyzer.html"),
        ruToolDiscordBot: resolve(__dirname, "src/pages/ru/tools/discord-bot.html"),
        adminDash: resolve(__dirname, "src/pages/admin/dashboard.html"),
        adminLogin: resolve(__dirname, "src/pages/admin/login.html"),
        adminUsers: resolve(__dirname, "src/pages/admin/users.html"),
        adminUser: resolve(__dirname, "src/pages/admin/user.html"),
        adminGens: resolve(__dirname, "src/pages/admin/generations.html"),
        adminGen: resolve(__dirname, "src/pages/admin/generation.html"),
        adminSubs: resolve(__dirname, "src/pages/admin/subscriptions.html"),
        adminTools: resolve(__dirname, "src/pages/admin/tools.html"),
        adminSettings: resolve(__dirname, "src/pages/admin/settings.html"),
        adminAiModels: resolve(__dirname, "src/pages/admin/ai-models.html"),
        adminLogs: resolve(__dirname, "src/pages/admin/logs.html"),
        adminContent: resolve(__dirname, "src/pages/admin/content.html"),
        adminContentEdit: resolve(__dirname, "src/pages/admin/content-edit.html"),
        faq: resolve(__dirname, "src/pages/faq.html"),
        blog: resolve(__dirname, "src/pages/blog.html"),
        blogPost: resolve(__dirname, "src/pages/blog-post.html"),
        offer: resolve(__dirname, "src/pages/offer.html"),
        contacts: resolve(__dirname, "src/pages/contacts.html"),
        ruFaq: resolve(__dirname, "src/pages/ru/faq.html"),
        ruBlog: resolve(__dirname, "src/pages/ru/blog.html"),
        ruBlogPost: resolve(__dirname, "src/pages/ru/blog-post.html"),
        ruOffer: resolve(__dirname, "src/pages/ru/offer.html"),
        ruContacts: resolve(__dirname, "src/pages/ru/contacts.html"),
      },
    },
  },
  server: {
    port: 3000,
    proxy: {
      "/api": {
        target: process.env.VITE_PROXY_TARGET || "http://api:8000",
        changeOrigin: true,
      },
      "/local-assets": {
        target: process.env.VITE_PROXY_TARGET || "http://api:8000",
        changeOrigin: true,
      },
    },
  },
});
